name: EAS Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm install -g eas-cli
      - uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}
      - run: eas build --platform android --profile preview --non-interactive
